---
# Location where configuration files will be stored.
config_dir: '~'

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: 'vcd.local'
domain_pihole: 'pihole2'          # to access pihole2 via: http://pihole2.vcd.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.vcd.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.vcd.local

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole2
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.in/;Google
  - https://github.com/;Github
  - https://www.apple.com/;Apple
  - https://vcdevs.net/;VCD

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - 'nodeexp:9100'
prometheus_extra_scrape_configs: ''
